### ISSUE TITLE
撤销 重做 bug  并且对图片进行打标有时候会双击右键两次才会失焦 

### ISSUE THREAD

**Issue by quhongli123** [opendatalab/labelU-Kit#506]
<img width="503" alt="image" src="https://github.com/user-attachments/assets/48440bef-f22b-4c1d-a1ec-295aec852356">

**Comment by gary-Shen** [comment]
好的，这是个已知问题，会尽快修复❤️。

**Comment by quhongli123** [comment]
> 需要右键两次才失去焦距是哪个工具？怎么恢复的？

https://opendatalab.github.io/labelU-Kit/#/image 就是咱们的案例 如果加一个带属性的  当弹窗内容写完关闭弹窗后需要右键两次才能取消命中当前的 选中的标注
