### ISSUE TITLE
提供 @labelu/image 使用文档

### ISSUE THREAD

**Issue by quhongli123** [opendatalab/labelU-Kit#507]
<img width="264" alt="image" src="https://github.com/user-attachments/assets/1b68118d-66e0-49b3-9c91-0e9c9c308a76">
example拿下来以后无法绘制

**Comment by gary-Shen** [comment]
更新了链接，可以在线访问看看：[stackblitz](https://stackblitz.com/github/opendatalab/labelU-Kit/tree/main/packages/image/example?file=vite.config.ts)

**Comment by quhongli123** [comment]
> 只下载了 example 目录启动吗？

对单独启动的example

**Comment by quhongli123** [comment]
> 更新了链接，可以在线访问查看：[stackblitz](https://stackblitz.com/github/opendatalab/labelU-Kit/tree/main/packages/image/example?file=vite.config.ts)

感谢  我试试看
