### ISSUE TITLE
请问下使用的Node的版本是多少呢？我在本地使用的时候一直报错找不到 @labelu/video-annotator-react/dist/style.css 

### ISSUE THREAD

**Issue by chenyurou297** [opendatalab/labelU-Kit#542]
![微信图片_20241205094113](https://github.com/user-attachments/assets/83e19b2f-b7ca-4a95-b415-32eacd08ae83)

**Comment by gary-Shen** [comment]
先运行pnpm build。workspace下用的是本地包。

**Comment by chenyurou297** [comment]
> 先运行pnpm build。workspace下用的是本地包。
