### ISSUE TITLE
所有输入框的删除键失效

### ISSUE THREAD

**Issue by gouxiwen** [opendatalab/labelU-Kit#543]
为什么所有输入框的删除键失效了？只能输入，不能删除？

**Comment by gary-Shen** [comment]
哪个界面？如何复现的？

**Comment by gouxiwen** [comment]
website页面的工具配置里的输入框都不能删除
![image](https://github.com/user-attachments/assets/dc63177a-5b24-444f-8ecc-c0ef2a7e63fa)

**Comment by gary-Shen** [comment]
OK，我们修复一下
